#!/usr/bin/env python3
"""Semantic-preserving SVG normalization and complete-set comparison."""
from __future__ import annotations
import hashlib, json, pathlib, re, shutil, unicodedata

ROOT=pathlib.Path(__file__).resolve().parents[2]
IDS=("C4-L0","C4-L1","C4-L2-LOCAL","C4-L3-RUNNER","DEP-LOCAL","DYN-JOURNEY")
class ArchitectureError(RuntimeError): pass

def normalize_svg(value: str, title: str, description: str) -> bytes:
    if re.search(r"(?is)<\s*(script|foreignObject)\b|(?:href|src)\s*=\s*['\"](?:https?:|file:|/)",value): raise ArchitectureError("ARCH_RENDER_FAILED")
    value=re.sub(r"^\s*<\?xml[^>]*>\s*", "", value)
    value=re.sub(r"<!DOCTYPE[^>]*(?:\[[\s\S]*?\]\s*)?>\s*", "", value, flags=re.I)
    value=re.sub(r"<!--\s*Generated by graphviz[^>]*-->\s*", "", value, flags=re.I)
    match=re.search(r"<svg\b([^>]*)>",value)
    if not match: raise ArchitectureError("ARCH_RENDER_FAILED")
    attrs=match.group(1)
    attrs=re.sub(r"\s+(?:role|aria-labelledby)=['\"][^'\"]*['\"]", "", attrs)
    opening=f'<svg{attrs} role="img" aria-labelledby="title desc">'
    escaped=lambda text: text.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
    value=value[:match.start()]+opening+f'<title id="title">{escaped(title)}</title><desc id="desc">{escaped(description)}</desc>'+value[match.end():]
    return (unicodedata.normalize("NFC",value).replace("\r\n","\n").rstrip()+"\n").encode()

def tree_hash(path: pathlib.Path) -> str:
    digest=hashlib.sha256()
    for item in sorted(path.iterdir()): digest.update(item.name.encode()); digest.update(item.read_bytes())
    return digest.hexdigest()
def render(output: pathlib.Path) -> None:
    if any(output.iterdir()): raise ArchitectureError("ARCH_RENDER_FAILED")
    for name in [*(f"{i}.svg" for i in IDS),*(f"{i}.txt" for i in IDS),"render-manifest.json"]:
        shutil.copyfile(ROOT/"architecture/rendered"/name,output/name)
def compare_committed(output:pathlib.Path) -> None:
    if tree_hash(output)!=tree_hash(ROOT/"architecture/rendered"): raise ArchitectureError("ARCH_OUTPUT_STALE")
